# Generated by Django 4.2.4 on 2024-09-22 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.FloatField()),
                ('budget_title', models.CharField(default='NULL', max_length=50)),
                ('education_budget', models.FloatField()),
                ('medical_budget', models.FloatField()),
                ('food_budget', models.FloatField()),
                ('entertainment_budget', models.FloatField()),
                ('transport_budget', models.FloatField()),
                ('personal_care_budget', models.FloatField()),
                ('housing_bills_budget', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=266)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_expense', to='Expenses.expense')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AiReportDateM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_monthly_budget', models.FloatField()),
                ('education_budget', models.FloatField()),
                ('medical_budget', models.FloatField()),
                ('food_budget', models.FloatField()),
                ('entertainment_budget', models.FloatField()),
                ('transport_budget', models.FloatField()),
                ('personal_care_budget', models.FloatField()),
                ('housing_bills_budget', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiReportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_weekly_budget', models.FloatField()),
                ('education_budget', models.FloatField()),
                ('medical_budget', models.FloatField()),
                ('food_budget', models.FloatField()),
                ('entertainment_budget', models.FloatField()),
                ('transport_budget', models.FloatField()),
                ('personal_care_budget', models.FloatField()),
                ('housing_bills_budget', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
